export const percentageImpactByIndustry: { key: string; value: number }[] = [
  { key: 'A', value: 5 },
  { key: 'B', value: 5 },
  { key: 'C', value: 80 },
  { key: 'D', value: 5 },
  { key: 'E', value: 10 },
  { key: 'F', value: 10 },
  { key: 'G', value: 10 },
  { key: 'H', value: 10 },
  { key: 'I', value: 80 },
  { key: 'J', value: 50 },
  { key: 'K', value: 70 },
  { key: 'L', value: 60 },
  { key: 'M', value: 50 },
  { key: 'N', value: 80 },
  { key: 'O', value: 20 },
  { key: 'P', value: 33 },
  { key: 'Q', value: 33 },
  { key: 'R', value: 40 },
  { key: 'S', value: 50 },
  { key: 'T', value: 20 },
  { key: 'U', value: 20 },
  { key: 'V', value: 33 },
];